version: "3"
services:
  wp-db:
    build: .
    image: mariadb
    network_mode: "host"
#    ports:
#      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wp_user
      MYSQL_PASSWORD: wordpress

