version: "3"
services:
  wordpress:
    image: wordpress
    restart: always
    network_mode: "host"
#    ports:
#      - "8000:80"
    environment:
      WORDPRESS_DB_HOST: mariadb:3306
      WORDPRESS_DB_USER: wp_user 
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
